services:
  - type: web
    name: spa-tasks
    env: static
    staticPublishPath: build
    buildCommand: npm install && npm run build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html